## Pandas

In [2]:
import pandas as pd 
import numpy as np

### DataFrame

In [29]:
# dataframe : it is the tabular representation of the data

basic = pd.DataFrame([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"], columns=["ok"])
print(basic)

details = {
    "name": ["raja", "Dhairya", "Raj"],
    "age": [12, 14, 15],
    "classes": [8, 9, 10],
}
details_dataframe =pd.DataFrame(details)
print(pd.DataFrame(details))

   ok
a   1
b   2
c   3
d   4
e   5
      name  age  classes
0     raja   12        8
1  Dhairya   14        9
2      Raj   15       10

### Dataframe Basics

In [ ]:
details_dataframe.head(1)#(x) i.e. x rows of the chart from begining

  name  age  classes
2  Raj   15       10

In [38]:
details_dataframe.tail(1)#(x) i.e. x rows of the chart ending

  name  age  classes
2  Raj   15       10

In [41]:
details_dataframe.shape#number of rows and coloumns

(3, 3)

In [43]:
details_dataframe.columns#gives the name of coloumns there present

Index(['name', 'age', 'classes'], dtype='str')

In [48]:
details_dataframe.rename(columns ={'classes': 'class'})#this only changes it till this command is run 


details_dataframe.rename(columns ={'classes': 'class'}, inplace =True)#this changes the name permanently

In [49]:
details_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   class   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [50]:
details_dataframe.describe()#this gives min , max , average , standard , 25%, 50% values

             age  class
count   3.000000    3.0
mean   13.666667    9.0
std     1.527525    1.0
min    12.000000    8.0
25%    13.000000    8.5
50%    14.000000    9.0
75%    14.500000    9.5
max    15.000000   10.0

### import csv File